# Generated by Django 5.0.4 on 2025-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_experience_job_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.URLField(unique=True),
        ),
    ]
